// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/mq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_proto_mq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	StatusCode    string                 `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_proto_mq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTopicResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateTopicResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *CreateTopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribeTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumerId,proto3" json:"consumerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTopicRequest) Reset() {
	*x = SubscribeTopicRequest{}
	mi := &file_proto_mq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTopicRequest) ProtoMessage() {}

func (x *SubscribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTopicRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeTopicRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type SubscribeTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	StatusCode    string                 `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeTopicResponse) Reset() {
	*x = SubscribeTopicResponse{}
	mi := &file_proto_mq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTopicResponse) ProtoMessage() {}

func (x *SubscribeTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTopicResponse.ProtoReflect.Descriptor instead.
func (*SubscribeTopicResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeTopicResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeTopicResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

type AckMsgRequets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,3,opt,name=consumerId,proto3" json:"consumerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMsgRequets) Reset() {
	*x = AckMsgRequets{}
	mi := &file_proto_mq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMsgRequets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMsgRequets) ProtoMessage() {}

func (x *AckMsgRequets) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMsgRequets.ProtoReflect.Descriptor instead.
func (*AckMsgRequets) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{4}
}

func (x *AckMsgRequets) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AckMsgRequets) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AckMsgRequets) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type AckMsgResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMsgResponse) Reset() {
	*x = AckMsgResponse{}
	mi := &file_proto_mq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMsgResponse) ProtoMessage() {}

func (x *AckMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMsgResponse.ProtoReflect.Descriptor instead.
func (*AckMsgResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{5}
}

func (x *AckMsgResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AckMsgResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PublishMsgsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMsgsData) Reset() {
	*x = PublishMsgsData{}
	mi := &file_proto_mq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMsgsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMsgsData) ProtoMessage() {}

func (x *PublishMsgsData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMsgsData.ProtoReflect.Descriptor instead.
func (*PublishMsgsData) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{6}
}

func (x *PublishMsgsData) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishMsgsData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishMsgsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishMsgsResponse) Reset() {
	*x = PublishMsgsResponse{}
	mi := &file_proto_mq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishMsgsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMsgsResponse) ProtoMessage() {}

func (x *PublishMsgsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMsgsResponse.ProtoReflect.Descriptor instead.
func (*PublishMsgsResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{7}
}

func (x *PublishMsgsResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishMsgsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ConsumeMsgsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeMsgsRequest) Reset() {
	*x = ConsumeMsgsRequest{}
	mi := &file_proto_mq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeMsgsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeMsgsRequest) ProtoMessage() {}

func (x *ConsumeMsgsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeMsgsRequest.ProtoReflect.Descriptor instead.
func (*ConsumeMsgsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{8}
}

func (x *ConsumeMsgsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeMsgsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConsumeMsgsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeMsgsData) Reset() {
	*x = ConsumeMsgsData{}
	mi := &file_proto_mq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeMsgsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeMsgsData) ProtoMessage() {}

func (x *ConsumeMsgsData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeMsgsData.ProtoReflect.Descriptor instead.
func (*ConsumeMsgsData) Descriptor() ([]byte, []int) {
	return file_proto_mq_proto_rawDescGZIP(), []int{9}
}

func (x *ConsumeMsgsData) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeMsgsData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ConsumeMsgsData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_mq_proto protoreflect.FileDescriptor

const file_proto_mq_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/mq.proto\x12\x06broker\"*\n" +
	"\x12CreateTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"f\n" +
	"\x13CreateTopicResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\tR\n" +
	"statusCode\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"M\n" +
	"\x15SubscribeTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"consumerId\x18\x02 \x01(\tR\n" +
	"consumerId\"O\n" +
	"\x16SubscribeTopicResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\tR\n" +
	"statusCode\"U\n" +
	"\rAckMsgRequets\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"consumerId\x18\x03 \x01(\tR\n" +
	"consumerId\":\n" +
	"\x0eAckMsgResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\";\n" +
	"\x0fPublishMsgsData\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"E\n" +
	"\x13PublishMsgsResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\":\n" +
	"\x12ConsumeMsgsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"K\n" +
	"\x0fConsumeMsgsData\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id2\xf9\x02\n" +
	"\rBrokerService\x12F\n" +
	"\vCreateTopic\x12\x1a.broker.CreateTopicRequest\x1a\x1b.broker.CreateTopicResponse\x12O\n" +
	"\x0eSubscribeTopic\x12\x1d.broker.SubscribeTopicRequest\x1a\x1e.broker.SubscribeTopicResponse\x12;\n" +
	"\n" +
	"AckMessage\x12\x15.broker.AckMsgRequets\x1a\x16.broker.AckMsgResponse\x12H\n" +
	"\x0eSetPublishData\x12\x17.broker.PublishMsgsData\x1a\x1b.broker.PublishMsgsResponse(\x01\x12H\n" +
	"\x0fSetConsumerData\x12\x1a.broker.ConsumeMsgsRequest\x1a\x17.broker.ConsumeMsgsData0\x01B!Z\x1fgithub.com/laithjas/kafgo/protob\x06proto3"

var (
	file_proto_mq_proto_rawDescOnce sync.Once
	file_proto_mq_proto_rawDescData []byte
)

func file_proto_mq_proto_rawDescGZIP() []byte {
	file_proto_mq_proto_rawDescOnce.Do(func() {
		file_proto_mq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mq_proto_rawDesc), len(file_proto_mq_proto_rawDesc)))
	})
	return file_proto_mq_proto_rawDescData
}

var file_proto_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_mq_proto_goTypes = []any{
	(*CreateTopicRequest)(nil),     // 0: broker.CreateTopicRequest
	(*CreateTopicResponse)(nil),    // 1: broker.CreateTopicResponse
	(*SubscribeTopicRequest)(nil),  // 2: broker.SubscribeTopicRequest
	(*SubscribeTopicResponse)(nil), // 3: broker.SubscribeTopicResponse
	(*AckMsgRequets)(nil),          // 4: broker.AckMsgRequets
	(*AckMsgResponse)(nil),         // 5: broker.AckMsgResponse
	(*PublishMsgsData)(nil),        // 6: broker.PublishMsgsData
	(*PublishMsgsResponse)(nil),    // 7: broker.PublishMsgsResponse
	(*ConsumeMsgsRequest)(nil),     // 8: broker.ConsumeMsgsRequest
	(*ConsumeMsgsData)(nil),        // 9: broker.ConsumeMsgsData
}
var file_proto_mq_proto_depIdxs = []int32{
	0, // 0: broker.BrokerService.CreateTopic:input_type -> broker.CreateTopicRequest
	2, // 1: broker.BrokerService.SubscribeTopic:input_type -> broker.SubscribeTopicRequest
	4, // 2: broker.BrokerService.AckMessage:input_type -> broker.AckMsgRequets
	6, // 3: broker.BrokerService.SetPublishData:input_type -> broker.PublishMsgsData
	8, // 4: broker.BrokerService.SetConsumerData:input_type -> broker.ConsumeMsgsRequest
	1, // 5: broker.BrokerService.CreateTopic:output_type -> broker.CreateTopicResponse
	3, // 6: broker.BrokerService.SubscribeTopic:output_type -> broker.SubscribeTopicResponse
	5, // 7: broker.BrokerService.AckMessage:output_type -> broker.AckMsgResponse
	7, // 8: broker.BrokerService.SetPublishData:output_type -> broker.PublishMsgsResponse
	9, // 9: broker.BrokerService.SetConsumerData:output_type -> broker.ConsumeMsgsData
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mq_proto_init() }
func file_proto_mq_proto_init() {
	if File_proto_mq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mq_proto_rawDesc), len(file_proto_mq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mq_proto_goTypes,
		DependencyIndexes: file_proto_mq_proto_depIdxs,
		MessageInfos:      file_proto_mq_proto_msgTypes,
	}.Build()
	File_proto_mq_proto = out.File
	file_proto_mq_proto_goTypes = nil
	file_proto_mq_proto_depIdxs = nil
}
