// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/mq.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrokerService_CreateTopic_FullMethodName     = "/broker.BrokerService/CreateTopic"
	BrokerService_SubscribeTopic_FullMethodName  = "/broker.BrokerService/SubscribeTopic"
	BrokerService_AckMessage_FullMethodName      = "/broker.BrokerService/AckMessage"
	BrokerService_SetPublishData_FullMethodName  = "/broker.BrokerService/SetPublishData"
	BrokerService_SetConsumerData_FullMethodName = "/broker.BrokerService/SetConsumerData"
)

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerServiceClient interface {
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error)
	SubscribeTopic(ctx context.Context, in *SubscribeTopicRequest, opts ...grpc.CallOption) (*SubscribeTopicResponse, error)
	AckMessage(ctx context.Context, in *AckMsgRequets, opts ...grpc.CallOption) (*AckMsgResponse, error)
	SetPublishData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PublishMsgsData, PublishMsgsResponse], error)
	SetConsumerData(ctx context.Context, in *ConsumeMsgsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsumeMsgsData], error)
}

type brokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerServiceClient(cc grpc.ClientConnInterface) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, BrokerService_CreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) SubscribeTopic(ctx context.Context, in *SubscribeTopicRequest, opts ...grpc.CallOption) (*SubscribeTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeTopicResponse)
	err := c.cc.Invoke(ctx, BrokerService_SubscribeTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) AckMessage(ctx context.Context, in *AckMsgRequets, opts ...grpc.CallOption) (*AckMsgResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckMsgResponse)
	err := c.cc.Invoke(ctx, BrokerService_AckMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) SetPublishData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PublishMsgsData, PublishMsgsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrokerService_ServiceDesc.Streams[0], BrokerService_SetPublishData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishMsgsData, PublishMsgsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrokerService_SetPublishDataClient = grpc.ClientStreamingClient[PublishMsgsData, PublishMsgsResponse]

func (c *brokerServiceClient) SetConsumerData(ctx context.Context, in *ConsumeMsgsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsumeMsgsData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrokerService_ServiceDesc.Streams[1], BrokerService_SetConsumerData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeMsgsRequest, ConsumeMsgsData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrokerService_SetConsumerDataClient = grpc.ServerStreamingClient[ConsumeMsgsData]

// BrokerServiceServer is the server API for BrokerService service.
// All implementations must embed UnimplementedBrokerServiceServer
// for forward compatibility.
type BrokerServiceServer interface {
	CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error)
	SubscribeTopic(context.Context, *SubscribeTopicRequest) (*SubscribeTopicResponse, error)
	AckMessage(context.Context, *AckMsgRequets) (*AckMsgResponse, error)
	SetPublishData(grpc.ClientStreamingServer[PublishMsgsData, PublishMsgsResponse]) error
	SetConsumerData(*ConsumeMsgsRequest, grpc.ServerStreamingServer[ConsumeMsgsData]) error
	mustEmbedUnimplementedBrokerServiceServer()
}

// UnimplementedBrokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrokerServiceServer struct{}

func (UnimplementedBrokerServiceServer) CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedBrokerServiceServer) SubscribeTopic(context.Context, *SubscribeTopicRequest) (*SubscribeTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribeTopic not implemented")
}
func (UnimplementedBrokerServiceServer) AckMessage(context.Context, *AckMsgRequets) (*AckMsgResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckMessage not implemented")
}
func (UnimplementedBrokerServiceServer) SetPublishData(grpc.ClientStreamingServer[PublishMsgsData, PublishMsgsResponse]) error {
	return status.Error(codes.Unimplemented, "method SetPublishData not implemented")
}
func (UnimplementedBrokerServiceServer) SetConsumerData(*ConsumeMsgsRequest, grpc.ServerStreamingServer[ConsumeMsgsData]) error {
	return status.Error(codes.Unimplemented, "method SetConsumerData not implemented")
}
func (UnimplementedBrokerServiceServer) mustEmbedUnimplementedBrokerServiceServer() {}
func (UnimplementedBrokerServiceServer) testEmbeddedByValue()                       {}

// UnsafeBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServiceServer will
// result in compilation errors.
type UnsafeBrokerServiceServer interface {
	mustEmbedUnimplementedBrokerServiceServer()
}

func RegisterBrokerServiceServer(s grpc.ServiceRegistrar, srv BrokerServiceServer) {
	// If the following call panics, it indicates UnimplementedBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrokerService_ServiceDesc, srv)
}

func _BrokerService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_SubscribeTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).SubscribeTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_SubscribeTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).SubscribeTopic(ctx, req.(*SubscribeTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_AckMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckMsgRequets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).AckMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrokerService_AckMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).AckMessage(ctx, req.(*AckMsgRequets))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_SetPublishData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrokerServiceServer).SetPublishData(&grpc.GenericServerStream[PublishMsgsData, PublishMsgsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrokerService_SetPublishDataServer = grpc.ClientStreamingServer[PublishMsgsData, PublishMsgsResponse]

func _BrokerService_SetConsumerData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumeMsgsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrokerServiceServer).SetConsumerData(m, &grpc.GenericServerStream[ConsumeMsgsRequest, ConsumeMsgsData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrokerService_SetConsumerDataServer = grpc.ServerStreamingServer[ConsumeMsgsData]

// BrokerService_ServiceDesc is the grpc.ServiceDesc for BrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "broker.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTopic",
			Handler:    _BrokerService_CreateTopic_Handler,
		},
		{
			MethodName: "SubscribeTopic",
			Handler:    _BrokerService_SubscribeTopic_Handler,
		},
		{
			MethodName: "AckMessage",
			Handler:    _BrokerService_AckMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SetPublishData",
			Handler:       _BrokerService_SetPublishData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SetConsumerData",
			Handler:       _BrokerService_SetConsumerData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mq.proto",
}
